#!/usr/bin/env bash
set -e -o pipefail

cd "$(dirname "$0")"

if [ "$SZ" == "7" ]; then
    cfg=configs/shc-evo2-7b-8k-2T-v2.yml
else
    cfg=configs/shc-evo2-40b-8k-11T-v2.yml
fi

CKPT=${CKPT:---dry_run}
DEFAULT_CMD="python3 generate.py $CKPT --config_path $cfg --debug"

run_args=(-it --rm
    --gpus=all
    --ipc=host --ulimit memlock=-1 --ulimit stack=67108864
    -v $PWD:/workdir
    vortex
    ${@:-$DEFAULT_CMD}
)

docker build -t vortex .
docker run "${run_args[@]}"
